#!/bin/sh
### BEGIN INIT INFO
# Provides:          ntpd
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     3 4 5
# Default-Stop:      0 1 2 6
# Short-Description: Calls ntpd once to sync with a remote timeserver
### END INIT INFO

# Variables
NAME=ntpd
DAEMON=/usr/sbin/$NAME
DAEMON_ARGS="-d -n -q" # -d: verbose logging, -n: do not daemonize, -q: quit after successful sync
PIDFILE=/var/run/$NAME.pid

# Exit if function script is not available
. /etc/init.d/functions || exit 1

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

case "$1" in
start)
    echo -n "Starting time sync"
    exec $DAEMON $DAEMON_ARGS
    ;;
*)
    echo "Usage: $0 start"
    ;;
esac

exit 0
